/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20PermitSol from "./ERC20Permit.sol";
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as ierc20MetadataSol from "./IERC20Metadata.sol";
export * as ierc20PermitSol from "./IERC20Permit.sol";
