/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20PermitSol from "./ERC20Permit.sol";
export type { erc20PermitSol };
import type * as erc20VotesSol from "./ERC20Votes.sol";
export type { erc20VotesSol };
import type * as ierc20MetadataSol from "./IERC20Metadata.sol";
export type { ierc20MetadataSol };
import type * as ierc20PermitSol from "./IERC20Permit.sol";
export type { ierc20PermitSol };
