/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as extensions from "./extensions";
export type { extensions };
