/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LitAgentWallet } from "./LitAgentWallet";
export type { VirtualsPolicy } from "./VirtualsPolicy";
export type { VirtualsToken } from "./VirtualsToken";
