/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc5267Sol from "./IERC5267.sol";
export * as ierc5805Sol from "./IERC5805.sol";
export * as ierc6372Sol from "./IERC6372.sol";
