/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc5267Sol from "./IERC5267.sol";
export type { ierc5267Sol };
import type * as ierc5805Sol from "./IERC5805.sol";
export type { ierc5805Sol };
import type * as ierc6372Sol from "./IERC6372.sol";
export type { ierc6372Sol };
